"""empty message

Revision ID: 611e1d524880
Revises: 6572b47d0c41
Create Date: 2024-10-19 10:19:12.237943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611e1d524880'
down_revision = '6572b47d0c41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('stock')

    # ### end Alembic commands ###
