"""empty message

Revision ID: a718086798f7
Revises: 611e1d524880
Create Date: 2024-10-19 10:22:27.027214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a718086798f7'
down_revision = '611e1d524880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publisher', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.drop_column('published_year')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_year', sa.INTEGER(), nullable=True))
        batch_op.drop_column('year')
        batch_op.drop_column('publisher')

    # ### end Alembic commands ###
